
apiVersion: v1
kind: Service
metadata:
  name: api-users-service
  labels:
    app: api-users
spec:
  selector:
    app: api-users
  ports:
    - protocol: TCP
      port: 64001
      targetPort: 64001
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: client-user-interface-service
spec:
  selector:
    app: client-user-interface
  ports:
    - protocol: TCP
      port: 63001
      targetPort: 63001
  type: LoadBalancer