
apiVersion: v1
kind: Service
metadata:
  name: api-users-service
  labels:
    app: api-users
spec:
  selector:
    app: api-users
  ports:
    - protocol: TCP
      port: 64001
      targetPort: 64001
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: client-user-interface-angular-service
  labels:
    app: client-user-interface-angular
spec:
  selector:
    app: client-user-interface-angular
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
