apiVersion: v1
kind: Service
metadata:
  name: api-users-service
spec:
  selector:
    app: api-users
  ports:
    - protocol: TCP
      port: 64001   
      targetPort: 64001   
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: auth-db-service
spec:
  selector:
    app: fullstack-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: client-user-interface-service
spec:
  selector:
    app: client-user-interface
  ports:
    - protocol: TCP
      port: 63001
      targetPort: 63001
  type: LoadBalancer
