services:
  api-users:
    image: ms-auth:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "64001:64001"
    environment:
      - PORT=64001
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_USER=devops
      - DB_PASS=devops
      - DB_NAME=auth_db_devops
      - JWT_SECRET=3lkfjhleg!sadfslhdfjso34393
    depends_on:
      - auth-db
    networks:
      - user-network-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api-users:3001/health"]
      interval: 30s
      retries: 5
      start_period: 40s
      timeout: 20s

  auth-db:
    image: postgres:14.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=devops   
      - POSTGRES_PASSWORD=devops    
      - POSTGRES_DB=auth_db_devops
    volumes:
      - auth-db-devops-data:/var/lib/postgresql/data
    networks:
      - user-network-app
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "devops", "-d", "auth_db_devops"]
      interval: 30s
      retries: 5
      start_period: 40s
      timeout: 20s

networks:
  user-network-app:
    driver: bridge

volumes:
  auth-db-devops-data:
